### ISSUE TITLE
Adds more structure to pillars

### ISSUE THREAD

**Issue by jeromepin** [valentin2105/Kubernetes-Saltstack#2]
Hi,

Could you consider adding more structure to pillars file ? Something like :
```
kubernetes:
  version: v1.8.6
  network:
    plugin: calico
    calico:
      CniVersion: v2.0.0
    enableIPv6: false
...
```

I'm gonna try your project. I may be able to provide a PR if you agree with that kind of changes.
