### ISSUE TITLE
docker data-root=/dockerFS should not be hardcoded 

### ISSUE THREAD

**Issue by rgroux** [valentin2105/Kubernetes-Saltstack#20]
in the pillar/cluster_config.sls file  there are an entry for the value of the docker data-root

```yaml
kubernetes:
...
  worker:
    runtime:
      docker:
        data-dir: /dockerFS
...
```

but in the `k8s-worker/cri/docker/docker.service` it's an hardcoded value --data-root=/dockerFS instead of something like `--data-root={{ salt['pillar.get']('kubernetes:worker:runtime:docker:data-dir') }}`.
