### ISSUE TITLE
Add Loadblancer feature

### ISSUE THREAD

**Issue by rgroux** [valentin2105/Kubernetes-Saltstack#23]
[Metallb](https://metallb.universe.tf)  can be nice to add the awesome LB services to the kubernetes cluster when it s a metal on, not an aws/google/azure.

i test and use it since a week, it work like a charm, i will make a ne PR for this after check how to enable it into the post_install service if you think it can be nice.

it will be a very short and simple PR, there are only 1 input parameter, the `External IP range`.

[Metallb tutorial for Layer 2](https://metallb.universe.tf/tutorial/layer2/)

**Comment by valentin2105** [comment]
Hi @rgroux,
It's really a great idea, and why not make it enableable from the pillar.
I looking forward for the PR   ;)

**Comment by rgroux** [comment]
hi @valentin2105 

yes indeed, 2 new params liste this

```yaml
kubernetes:
   loadbalancer:
     enable: true
     type: metallb
     version: v0.7.3
     ranges: ["10.0.0.0/24"]
```

i wait for the PR, because i wish to try with traefik too
